# Javascirpt

[Promise](#promise)  
[async](#async)  

## Promise
```javascript
let p = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('abc')},3000 );
    // setTimeout(()=>{reject('abc')},3000 );
})
.then((data) => {
    console.log(data);
})
.catch((error) => {
    console.log(error);
})
.finally(() => {
    console.log('close');
})
```
Promise.all([p1,p2,p3]) 都resolve才resolve，有一个reject就reject
```javascript
let p1 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('a')}, 1000);
});

let p2 = new Promise((resolve, reject)=>{
    setTimeout(()=>{reject('b')}, 2000);
})

let p3 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('c')}, 3000);
})

let p = Promise.all([p1, p2, p3]);
p.then((data)=>{
    console.log(data);
})
.catch((error)=>{
    console.log(error)
})
// b
```

```javascript
let p1 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('a')}, 1000);
});

let p2 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('b')}, 2000);
})

let p3 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('c')}, 3000);
})

let p = Promise.all([p1, p2, p3]);
p.then((data)=>{
    console.log(data);
})
.catch((error)=>{
    console.log(error)
})
// ["a", "b", "c"]
```

Promise.race() 有一个返回就返回
```javascript
let p1 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('a')}, 1000);
});

let p2 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('b')}, 2000);
})

let p3 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('c')}, 3000);
})

let p = Promise.race([p1, p2, p3]);
p.then((data)=>{
    console.log(data);
})
.catch((error)=>{
    console.log(error)
})
// "a"
```

```javascript
let p1 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('a')}, 4000);
});

let p2 = new Promise((resolve, reject)=>{
    setTimeout(()=>{reject('b')}, 1000);
})

let p3 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('c')}, 3000);
})

let p = Promise.race([p1, p2, p3]);
p.then((data)=>{
    console.log(data);
})
.catch((error)=>{
    console.log(error)
})
// "b"
```

Promise.allSettled() 都返回值才会返回
```javascript
let p1 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('a')}, 4000);
});

let p2 = new Promise((resolve, reject)=>{
    setTimeout(()=>{reject('b')}, 1000);
})

let p3 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('c')}, 3000);
})

let p = Promise.allSettled([p1, p2, p3]);
p.then((data)=>{
    console.log(data);
})

/*
[
{status: "fulfilled", value: "a"},
{status: "rejected", reason: "b"},
{status: "fulfilled", value: "c"}
]
*/
```

Promise.any() 有一个resolve就resolve，都reject才会reject
```javascript
let p1 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('a')}, 4000);
});

let p2 = new Promise((resolve, reject)=>{
    setTimeout(()=>{reject('b')}, 1000);
})

let p3 = new Promise((resolve, reject)=>{
    setTimeout(()=>{resolve('c')}, 3000);
})

let p = Promise.any([p1, p2, p3]);
p.then((data)=>{
    console.log(data);
})

/*
c
*/
```

```javascript
let p1 = new Promise((resolve, reject)=>{
    setTimeout(()=>{reject('a')}, 4000);
});

let p2 = new Promise((resolve, reject)=>{
    setTimeout(()=>{reject('b')}, 1000);
})

let p3 = new Promise((resolve, reject)=>{
    setTimeout(()=>{reject('c')}, 3000);
})

let p = Promise.any([p1, p2, p3]);
p.then((data)=>{
    console.log(data);
})
.catch((error)=>{
    console.log(error);
})

/*
AggregateError: All promises were rejected
*/
```

## async
[Top](#javascript)

### async函数返回值是promise对象  
### await后面是promise对象或者是原始数据类型（会转化为promise对象）  
### await后面的表达式的返回是promise对象的resolve或者reject的值  
### async函数的return值是async函数返回的promise的then的参数  


```javascript
function st1(name){
    let p1 = new Promise((resolve, reject) => {
        setTimeout(()=>{
            resolve(name)
        }, 2000);
    })
    return p1;
}

function st2(name){
    let p2 = new Promise((resolve, reject) => {
        setTimeout(()=>{
            resolve(name)
        }, 2000);
    })
    return p2;
}

async function st(name1, name2){
    let name11 = await st1(name1);
    let name22 = await st2(name2);
    return {name11, name22}
}

st('php', 'js')
.then((data)=>{
    console.log(data)
})
;
```

### 任何一个await语句后面的 Promise 对象变为reject状态，那么整个async函数都会中断执行。
### await命令后面的 Promise 对象如果变为reject状态，则reject的参数会被catch方法的回调函数接收到。
### async函数内部抛出错误，会导致返回的 Promise 对象变为reject状态。抛出的错误对象会被catch方法回调函数接收到。
```javascript
function st1(name){
    let p1 = new Promise((resolve, reject) => {
        setTimeout(()=>{
            reject(name)
        }, 2000);
    })
    return p1;
}

function st2(name){
    let p2 = new Promise((resolve, reject) => {
        setTimeout(()=>{
            resolve(name)
        }, 2000);
    })
    return p2;
}

async function st(name1, name2){
    let name11 = await st1(name1);
    let name22 = await st2(name2);
    return {name11, name22}
}

st('php', 'js')
.then((data)=>{
    console.log(data)
})
.catch((error)=>{
    console.log(error)
})
;
// php
```

### 事件循环
https://www.jianshu.com/p/9644f13568c0


